language: python
python:
  - "3.9"

cache:
  directories:
    - "~/.platformio"

env:
  global:
    - PLATFORMIO_BUILD_FLAGS="-w"
  matrix:
    - PLATFORMIO_CI_SRC="examples/CustomV1/CustomV1.cpp" PROJECT_CONF="examples/CustomV1/CustomV1.ini"
    - PLATFORMIO_CI_SRC="examples/CustomV2/CustomV2.cpp" PROJECT_CONF="examples/CustomV2/CustomV2.ini"
    - PLATFORMIO_CI_SRC="examples/CustomV3/CustomV3.cpp" PROJECT_CONF="examples/CustomV3/CustomV3.ini"
    - PLATFORMIO_CI_SRC="examples/SonoffBasic/SonoffBasic.cpp" PROJECT_CONF="examples/SonoffBasic/SonoffBasic.ini"
    - PLATFORMIO_CI_SRC="examples/SonoffS20/SonoffS20.cpp" PROJECT_CONF="examples/SonoffS20/SonoffS20.ini"

install:
  - pip install -U platformio

  # Libraries from PlatformIO Library Registry:
  #
  # https://platformio.org/lib/show/64/ArduinoJson
  # https://platformio.org/lib/show/1671/DHT
  # https://platformio.org/lib/show/617/MQTT
  # https://platformio.org/lib/show/560/Streaming
  - platformio lib -g install 64@5.13.2 1671@1.0.0 617@2.4.3 560@5

script:
  - platformio ci --lib="." --project-conf=$PROJECT_CONF
