language: python
python:
  - "2.7"

sudo: false

cache:
  directories:
    - "~/.platformio"

env:
  global:
    - PLATFORMIO_BUILD_FLAGS="-Werror"
  matrix:
    - PLATFORMIO_CI_SRC="examples/CustomV1/CustomV1.cpp" PROJECT_CONF="examples/CustomV1/CustomV1.ini"
    - PLATFORMIO_CI_SRC="examples/CustomV2/CustomV2.cpp" PROJECT_CONF="examples/CustomV2/CustomV2.ini"
    - PLATFORMIO_CI_SRC="examples/CustomV3/CustomV3.cpp" PROJECT_CONF="examples/CustomV3/CustomV3.ini"
    - PLATFORMIO_CI_SRC="examples/SonoffBasic/SonoffBasic.cpp" PROJECT_CONF="examples/SonoffBasic/SonoffBasic.ini"
    - PLATFORMIO_CI_SRC="examples/SonoffS20/SonoffS20.cpp" PROJECT_CONF="examples/SonoffS20/SonoffS20.ini"

install:
  - pip install -U platformio
  - platformio lib -g install ArduinoJson@~5.10.0 MQTT@~2.4.3 Streaming@5

script:
  - platformio ci --lib="." --project-conf=$PROJECT_CONF
