language: python
python:
  - "2.7"

sudo: false

cache:
  directories:
    - "~/.platformio"

env:
  global:
    - PLATFORMIO_BUILD_FLAGS="-Werror"
  matrix:
    - PLATFORMIO_CI_SRC="examples/Custom/Custom.cpp" PROJECT_CONF="examples/Custom/Custom.ini"
    - PLATFORMIO_CI_SRC="examples/CustomV2/CustomV2.cpp" PROJECT_CONF="examples/CustomV2/CustomV2.ini"
    - PLATFORMIO_CI_SRC="examples/SonoffBasic/SonoffBasic.cpp" PROJECT_CONF="examples/SonoffBasic/SonoffBasic.ini"
    - PLATFORMIO_CI_SRC="examples/SonoffS20/SonoffS20.cpp" PROJECT_CONF="examples/SonoffS20/SonoffS20.ini"

install:
  - pip install -U platformio
  - platformio lib -g install ArduinoJson@~5.10.0 PubSubClient@~2.6 Streaming@5

script:
  - platformio ci --lib="." --project-conf=$PROJECT_CONF
