# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install PlatformIO
          command: sudo pip install platformio
      - restore_cache:
          keys:
          - v1-dependencies
      - run:
          name: Install dependencies
          command: platformio lib -g install ArduinoJson@~5.10.0 PubSubClient@~2.6 Streaming@5
      - run:
          name: Run build for custom board
          command: platformio ci examples/Custom/Custom.cpp --lib="." --project-conf="examples/Custom/Custom.ini"
          environment:
            PLATFORMIO_BUILD_FLAGS: -Werror
      - run:
          name: Run build for Sonoff Basic board
          command: platformio ci examples/SonoffBasic/SonoffBasic.cpp --lib="." --project-conf="examples/SonoffBasic/SonoffBasic.ini"
          environment:
            PLATFORMIO_BUILD_FLAGS: -Werror
      - run:
          name: Run build for Sonoff S20 board
          command: platformio ci examples/SonoffS20/SonoffS20.cpp --lib="." --project-conf="examples/SonoffS20/SonoffS20.ini"
          environment:
            PLATFORMIO_BUILD_FLAGS: -Werror
      - save_cache:
          key: v1-dependencies-{{ epoch }}
          paths:
            - ~/.platformio
